/// Flutter icons Airplane
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Airplane
///      fonts:
///       - asset: fonts/Airplane.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Airplane {
  Airplane._();

  static const _kFontFam = 'Airplane';
  static const _kFontPkg = null;

  static const IconData plane_departure_solid = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
