/// Flutter icons Maps
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Maps
///      fonts:
///       - asset: fonts/Maps.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Maps {
  Maps._();

  static const _kFontFam = 'Maps';
  static const _kFontPkg = null;

  static const IconData map_marker_alt_solid = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
